// Generated by gencpp from file shared_files/Bucket.msg
// DO NOT EDIT!


#ifndef SHARED_FILES_MESSAGE_BUCKET_H
#define SHARED_FILES_MESSAGE_BUCKET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace shared_files
{
template <class ContainerAllocator>
struct Bucket_
{
  typedef Bucket_<ContainerAllocator> Type;

  Bucket_()
    : dump(0.0)  {
    }
  Bucket_(const ContainerAllocator& _alloc)
    : dump(0.0)  {
  (void)_alloc;
    }



   typedef float _dump_type;
  _dump_type dump;




  typedef boost::shared_ptr< ::shared_files::Bucket_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shared_files::Bucket_<ContainerAllocator> const> ConstPtr;

}; // struct Bucket_

typedef ::shared_files::Bucket_<std::allocator<void> > Bucket;

typedef boost::shared_ptr< ::shared_files::Bucket > BucketPtr;
typedef boost::shared_ptr< ::shared_files::Bucket const> BucketConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::shared_files::Bucket_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::shared_files::Bucket_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace shared_files

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'shared_files': ['/home/issa/AGGREGATOR_WS/src/shared_files/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::Bucket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::shared_files::Bucket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::Bucket_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::shared_files::Bucket_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::Bucket_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::shared_files::Bucket_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::shared_files::Bucket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2f320488a93a2b8fbcde81ea62701ed";
  }

  static const char* value(const ::shared_files::Bucket_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2f320488a93a2b8ULL;
  static const uint64_t static_value2 = 0xfbcde81ea62701edULL;
};

template<class ContainerAllocator>
struct DataType< ::shared_files::Bucket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "shared_files/Bucket";
  }

  static const char* value(const ::shared_files::Bucket_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::shared_files::Bucket_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 dump\n\
\n\
";
  }

  static const char* value(const ::shared_files::Bucket_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::shared_files::Bucket_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dump);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bucket_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shared_files::Bucket_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::shared_files::Bucket_<ContainerAllocator>& v)
  {
    s << indent << "dump: ";
    Printer<float>::stream(s, indent + "  ", v.dump);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SHARED_FILES_MESSAGE_BUCKET_H
