// Generated by gencpp from file shared_files/ReadI2C.msg
// DO NOT EDIT!


#ifndef SHARED_FILES_MESSAGE_READI2C_H
#define SHARED_FILES_MESSAGE_READI2C_H

#include <ros/service_traits.h>


#include <shared_files/ReadI2CRequest.h>
#include <shared_files/ReadI2CResponse.h>


namespace shared_files
{

struct ReadI2C
{

typedef ReadI2CRequest Request;
typedef ReadI2CResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadI2C
} // namespace shared_files


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::shared_files::ReadI2C > {
  static const char* value()
  {
    return "22e5f5eaf6ee0bc3b5bf519623591445";
  }

  static const char* value(const ::shared_files::ReadI2C&) { return value(); }
};

template<>
struct DataType< ::shared_files::ReadI2C > {
  static const char* value()
  {
    return "shared_files/ReadI2C";
  }

  static const char* value(const ::shared_files::ReadI2C&) { return value(); }
};


// service_traits::MD5Sum< ::shared_files::ReadI2CRequest> should match 
// service_traits::MD5Sum< ::shared_files::ReadI2C > 
template<>
struct MD5Sum< ::shared_files::ReadI2CRequest>
{
  static const char* value()
  {
    return MD5Sum< ::shared_files::ReadI2C >::value();
  }
  static const char* value(const ::shared_files::ReadI2CRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::shared_files::ReadI2CRequest> should match 
// service_traits::DataType< ::shared_files::ReadI2C > 
template<>
struct DataType< ::shared_files::ReadI2CRequest>
{
  static const char* value()
  {
    return DataType< ::shared_files::ReadI2C >::value();
  }
  static const char* value(const ::shared_files::ReadI2CRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::shared_files::ReadI2CResponse> should match 
// service_traits::MD5Sum< ::shared_files::ReadI2C > 
template<>
struct MD5Sum< ::shared_files::ReadI2CResponse>
{
  static const char* value()
  {
    return MD5Sum< ::shared_files::ReadI2C >::value();
  }
  static const char* value(const ::shared_files::ReadI2CResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::shared_files::ReadI2CResponse> should match 
// service_traits::DataType< ::shared_files::ReadI2C > 
template<>
struct DataType< ::shared_files::ReadI2CResponse>
{
  static const char* value()
  {
    return DataType< ::shared_files::ReadI2C >::value();
  }
  static const char* value(const ::shared_files::ReadI2CResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SHARED_FILES_MESSAGE_READI2C_H
