(cl:defpackage shared_files-srv
  (:use )
  (:export
   "READI2C"
   "<READI2C-REQUEST>"
   "READI2C-REQUEST"
   "<READI2C-RESPONSE>"
   "READI2C-RESPONSE"
   "READI2CREGISTER"
   "<READI2CREGISTER-REQUEST>"
   "READI2CREGISTER-REQUEST"
   "<READI2CREGISTER-RESPONSE>"
   "READI2CREGISTER-RESPONSE"
  ))

